# Generated by Django 5.0.7 on 2024-08-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_project_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Canceled', 'Canceled'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], default='Active', max_length=10, null=True),
        ),
    ]
