# Generated by Django 4.2 on 2024-08-15 12:11

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0007_alter_project_name_alter_project_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='home_address',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.CreateModel(
            name='ProjectSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_site_cordinates', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('area', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('way_from_home', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
