# Generated by Django 4.2 on 2024-08-16 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0008_remove_profile_address_profile_home_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectsite',
            old_name='user',
            new_name='creator',
        ),
        migrations.AddField(
            model_name='projectsite',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.project'),
        ),
    ]
